# Generated by Django 5.0.4 on 2024-05-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comment',
        ),
        migrations.AddField(
            model_name='product',
            name='comment',
            field=models.ManyToManyField(to='products.comment'),
        ),
    ]
